version: '2'
services:
  mongodb:
    image: mongo
    volumes: 
      -mongo_data: /data/db
    ports:
      - '27017:27017'
    
  mongo-express:
    image: mongo-express
    ports:
      - '8081:8081'
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
    depends_on:
      - mongodb
#El servicio mongo-express no se iniciará hasta que mongodb este iniciado

volumes:
  mongo_data:

networks:
  default:
    driver: bridge



