version: '3.1'
services:
  mongo:    #Creamos dos contenedores, uno llamado "mongo" y otro llamado "mongo-express"
    image: mongo:latest  #imagen que usar치 el contenedor mongo
    restart: always
    ports:
      - 27017:27017   #mapeamos los puertos 
    volumes:  
      - mongo-data:/data/db   #Creamos un volumen para que los datos persistan en caso de que queramos crear otro contenedor con la misma bd
    networks:
      mongo-net:
        ipv4_address: 172.31.21.227   #Asignamos una ip de la network mongo-net definida mas abajo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root      #variables de entorno, que ser치n el nombre de usuario y contrase침a del admin
      MONGO_INITDB_ROOT_PASSWORD: example
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    volumes:
      - mongo-express-data:/home/mongo-express
    networks:
      mongo-net:
        ipv4_address: 172.31.21.228
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/  #indica la conexi칩n a la bd
volumes:    #definimos los volumenes usados, indicando el driver local que usaremos
  mongo-data:
    driver: local
  mongo-express-data:
    driver: local 
networks: #definimos la red que usaremos para que los contenedores se comuniquen
  mongo-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.31.0.0/16