version: '2'
services:
  mongodb:
    image: mongo
    volumes: 
      - 'mongo_data:/data/db'
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password

    networks:
      - dockerdaw_netowrk
    
  mongo-express:
    image: mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_mongo_ADMINUSERNAME: admin
      ME_CONFIG_mongo_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_SERVER: mongodb
    networks:
      - dockerdaw_netowrk
    depends_on:
      - mongodb
#El servicio mongo-express no se iniciará hasta que mongo este iniciado
volumes:
  mongo_data:
    driver: local
networks:
  dockerdaw_netowrk:
    driver: bridge



