version: '3.1'

services:

  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: toor
    volumes:
      - 'mi-mongo-vol:/app/data/bd'
    networks:
      mi-mongo-red:
        ipv4_address: 172.30.0.4
  mongo-express:
    image: mongo-express
    ports:
      - '8081:8081'
    depends_on:
      - mongo
    networks:
      mi-mongo-red:
        ipv4_address: 172.30.0.5
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: toor
      ME_CONFIG_MONGODB_URL: mongodb://root:toor@mongo:27017/

volumes:
  mi-mongo-vol:
    driver: local
  mi-mongo-express-vol:
    driver: local
networks:
    mi-mongo-red:
      driver: bridge
      ipam:
        config:
          - subnet: 172.30.0.0/16
