version: '2'
services:
  mongo:
    image: mongo
    restart: unless-stopped
    volumes: 
      - 'mongo_data:/data/db'
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password

  mongo-express:
    image: mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_mongo_ADMINUSERNAME: admin
      ME_CONFIG_mongo_ADMINPASSWORD: password
      ME_CONFIG_mongo_URL: mongodb://admin:password@mongo:27017/

    depends_on:
      - mongo
#El servicio mongo-express no se iniciará hasta que mongo este iniciado
volumes:
  mongo_data:
    driver: local

networks:
  mongoNetWork:
    driver: bridge

